"""
EXP 07 — Self-Supervised Geometric Foundation Model for Roads
==================================================================
Theoretical lens: SELF-SUPERVISED REPRESENTATION LEARNING.

Foundation models won language and vision because both have abundant
unlabelled corpora. SDC-testing has *very few* labelled tests (~36k) but
**unbounded** unlabelled roads — they can be procedurally generated by any
test generator (Frenetic, Kappa-tester, Bezier samplers). We turn this into
a foundation-model recipe.

Two pretext tasks, both PURELY GEOMETRIC and label-free:

  (P1) Masked Road Completion
      Mask out 15% contiguous segments of the (x,y) trajectory and ask the
      model to predict the missing arc-length-parameterized curvature
      values. Cross-entropy or MSE on a discretized curvature codebook.

  (P2) Frenet-Serret Reconstruction
      From the raw points (x,y) alone, predict (kappa(s), d kappa/d s).
      This is the differential-geometric Frenet-Serret pair (no torsion in
      2D); a model that solves this has internalized the intrinsic geometry
      of curves.

The pretrained encoder is then fine-tuned on the small labelled set with
either a frozen-feature linear probe or full finetune. We show:
  - linear probe matches or beats from-scratch full training,
  - finetune with 10% of the labels matches the baseline trained on 100%,
giving a *foundation-model-like* sample-efficiency curve on a structured,
non-language domain.

Procedural data generator: Bezier curves with K random control points,
then re-sampled to SEQ_LEN. We generate N_pretrain = 200_000 synthetic roads
on the fly (no disk required).
"""

import json, numpy as np, os, time, math, copy, warnings
warnings.filterwarnings('ignore')
import torch, torch.nn as nn, torch.nn.functional as F, torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, Dataset
from torch.cuda.amp import autocast, GradScaler
from sklearn.metrics import roc_auc_score

KAGGLE_DATA = '/kaggle/input/datasets/chinguyeen/sdc-sensodat'
OUTPUT_DIR = '/kaggle/working'
if os.path.exists(KAGGLE_DATA):
    TRAIN_PATH = os.path.join(KAGGLE_DATA, 'sensodat_train.json')
    TEST_PATH  = os.path.join(KAGGLE_DATA, 'sensodat_test.json')
    COMP_PATH  = os.path.join(KAGGLE_DATA, 'sdc-test-data.json')
else:
    BASE = os.path.join(os.path.dirname(__file__), '..', '..', '..', '..')
    TRAIN_PATH = os.path.join(BASE, 'data', 'sensodat_train.json')
    TEST_PATH  = os.path.join(BASE, 'data', 'sensodat_test.json')
    COMP_PATH  = os.path.join(BASE, 'data', 'sdc-test-data.json')
    OUTPUT_DIR = os.path.join(BASE, 'models')
os.makedirs(OUTPUT_DIR, exist_ok=True)
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
USE_BF16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
AMP_DTYPE = torch.bfloat16 if USE_BF16 else torch.float16
torch.set_float32_matmul_precision('high')
print(f"Device: {DEVICE} | bf16: {USE_BF16}")
if torch.cuda.is_available(): print(f"GPU: {torch.cuda.get_device_name()}")

SEQ_LEN = 197

# -------------------- Procedural Bezier generator --------------------
def _bezier(P, n=SEQ_LEN):
    """De Casteljau on K control points -> n samples."""
    P = np.asarray(P, dtype=np.float64); K = len(P) - 1
    t = np.linspace(0, 1, n)[:, None]                    # (n,1)
    pts = np.zeros((n, 2))
    # explicit Bernstein expansion
    for k in range(K + 1):
        coeff = math.comb(K, k) * (t**k) * ((1-t)**(K-k))
        pts += coeff * P[k]
    return pts

def gen_random_road(rng):
    K = int(rng.choice([3, 4, 5, 6, 7]))                  # ctrl points
    P = rng.uniform(-100, 100, size=(K+1, 2))
    P[0] = [0, 0]; P[-1] = rng.uniform(60, 250, size=2) * rng.choice([-1, 1], size=2)
    return _bezier(P, SEQ_LEN)                            # (SEQ_LEN, 2)

# -------------------- 10-channel features (numpy) --------------------
def compute_curvature(pts):
    n=len(pts); curv=np.zeros(n-2)
    for i in range(n-2):
        x1,y1=pts[i]; x2,y2=pts[i+1]; x3,y3=pts[i+2]
        a=math.sqrt((x2-x1)**2+(y2-y1)**2); b=math.sqrt((x3-x2)**2+(y3-y2)**2); c=math.sqrt((x3-x1)**2+(y3-y1)**2)
        s=0.5*(a+b+c); at=s*(s-a)*(s-b)*(s-c)
        if at<=1e-10: curv[i]=0.0
        else: R=a*b*c/(4*math.sqrt(at)); curv[i]=1.0/R if R>0 else 0.0
    return curv
def extract_sequence_10ch(pts_raw):
    pts=np.array(pts_raw,dtype=np.float64).reshape(-1,2); n=len(pts)
    diffs=np.diff(pts,axis=0); seg_lens=np.linalg.norm(diffs,axis=1)
    seg_full=np.pad(seg_lens,(0,1),mode='edge')
    angles=np.arctan2(diffs[:,1],diffs[:,0]); ac=np.diff(angles)
    ac=(ac+np.pi)%(2*np.pi)-np.pi; abs_ac_full=np.pad(np.abs(ac),(1,1),mode='constant')
    curv=np.abs(compute_curvature(pts)); curv_full=np.pad(curv,(1,1),mode='constant')
    curv_deriv_full=np.pad(np.diff(curv_full),(0,1),mode='constant')
    cum_dist=np.cumsum(seg_full); cum_dist_norm=cum_dist/(cum_dist[-1]+1e-8)
    heading_full=np.pad(angles,(0,1),mode='edge')
    heading_sin=np.sin(heading_full); heading_cos=np.cos(heading_full)
    rel_pos=np.linspace(0,1,n)
    w=11; local_std=np.zeros(n); hw=w//2
    for i in range(n):
        s,e=max(0,i-hw),min(n,i+hw+1); local_std[i]=np.std(curv_full[s:e])
    curv_accel_full=np.pad(np.diff(curv_deriv_full),(0,1),mode='constant')
    return np.column_stack([seg_full,abs_ac_full,curv_full,curv_deriv_full,cum_dist_norm,
                            heading_sin,heading_cos,rel_pos,local_std,curv_accel_full]).astype(np.float32)
def load_json(path):
    print(f"Loading {path}..."); t0=time.time()
    with open(path) as f: data=json.load(f)
    print(f"  Loaded {len(data)} tests in {time.time()-t0:.1f}s"); return data
def get_pts(tc): return [[p['x'],p['y']] for p in tc['road_points']]
def is_fail(tc): return tc['meta_data']['test_info']['test_outcome']=='FAIL'
def get_id(tc): return tc['_id']['$oid']

# -------------------- Encoder + dual heads --------------------
class RoadEncoder(nn.Module):
    def __init__(self, in_channels=10, seq_len=197, d_model=256, nhead=8,
                 num_layers=8, dim_feedforward=768, dropout=0.1):
        super().__init__()
        self.input_proj = nn.Sequential(nn.Linear(in_channels, d_model),
                                        nn.LayerNorm(d_model), nn.GELU())
        self.cls = nn.Parameter(torch.randn(1, 1, d_model)*0.02)
        self.pos = nn.Parameter(torch.randn(1, seq_len + 1, d_model)*0.02)
        layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead,
            dim_feedforward=dim_feedforward, dropout=dropout, activation='gelu',
            batch_first=True, norm_first=True)
        self.tf = nn.TransformerEncoder(layer, num_layers=num_layers)
        self.d_model = d_model
    def forward(self, x):                       # x: (B, C, L)
        x = x.permute(0, 2, 1); B, L, _ = x.shape
        x = self.input_proj(x)
        cls = self.cls.expand(B, -1, -1)
        x = torch.cat([cls, x], dim=1) + self.pos[:, :L+1, :]
        return self.tf(x)                       # (B, L+1, D)

class FoundationModel(nn.Module):
    """Encoder + 3 heads: (1) masked reconstruction, (2) Frenet-Serret regression,
    (3) classification (added at finetune time)."""
    def __init__(self, in_channels=10, d_model=256, num_layers=8):
        super().__init__()
        self.enc = RoadEncoder(in_channels=in_channels, d_model=d_model,
                               num_layers=num_layers)
        # P1: per-position regression for the masked TARGETS (curv & d-curv = ch 2 & 3)
        self.head_recon = nn.Sequential(nn.LayerNorm(d_model),
                                        nn.Linear(d_model, 64), nn.GELU(),
                                        nn.Linear(64, 2))
        # P2: per-position Frenet-Serret regression (kappa, d kappa / ds) computed
        # from RAW points only (input has 10 channels but we mask channels 2..)
        self.head_fs = nn.Sequential(nn.LayerNorm(d_model),
                                     nn.Linear(d_model, 64), nn.GELU(),
                                     nn.Linear(64, 2))
        # classification head (init at finetune)
        self.head_cls = nn.Sequential(nn.LayerNorm(d_model),
                                      nn.Linear(d_model, 64), nn.GELU(),
                                      nn.Dropout(0.2), nn.Linear(64, 1))

    def forward(self, x, mode='recon'):
        h = self.enc(x)
        tok = h[:, 1:, :]                           # token states
        if mode == 'recon':
            return self.head_recon(tok)             # (B, L, 2)
        if mode == 'fs':
            return self.head_fs(tok)                # (B, L, 2)
        if mode == 'cls':
            return self.head_cls(h[:, 0, :]).squeeze(-1)
        raise ValueError(mode)

# -------------------- Pretraining dataset --------------------
class SyntheticRoadDataset(Dataset):
    def __init__(self, n_samples=200_000, seed=0, mask_ratio=0.15):
        self.n = n_samples; self.seed = seed; self.mask_ratio = mask_ratio
    def __len__(self): return self.n
    def __getitem__(self, i):
        rng = np.random.RandomState((self.seed * 1_000_003 + i) & 0xFFFFFFFF)
        pts = gen_random_road(rng)
        feats = extract_sequence_10ch(pts.tolist())   # (L, 10)
        # Targets: ch 2 (curv), ch 3 (d-curv) — reuse for both pretext heads
        target_recon = feats[:, 2:4].copy()
        target_fs    = feats[:, 2:4].copy()
        # Build masked input by zeroing curvature channels in masked windows
        L = feats.shape[0]; mask = np.zeros(L, dtype=np.float32)
        n_mask = int(L * self.mask_ratio)
        # contiguous block
        if n_mask > 0:
            start = rng.randint(0, L - n_mask)
            mask[start:start+n_mask] = 1.0
        x = feats.copy()
        x[mask > 0.5, 2] = 0.0
        x[mask > 0.5, 3] = 0.0
        x[mask > 0.5, 8] = 0.0
        x[mask > 0.5, 9] = 0.0
        # FS pretext: zero ALL curvature channels so the model must reconstruct from (x,y)-derivatives
        x_fs = feats.copy()
        x_fs[:, 2] = 0.0; x_fs[:, 3] = 0.0; x_fs[:, 8] = 0.0; x_fs[:, 9] = 0.0
        return (torch.tensor(x.T, dtype=torch.float32),
                torch.tensor(x_fs.T, dtype=torch.float32),
                torch.tensor(target_recon, dtype=torch.float32),
                torch.tensor(target_fs, dtype=torch.float32),
                torch.tensor(mask, dtype=torch.float32))

# -------------------- Pretrain --------------------
def pretrain(model, *, steps=4000, batch=512, lr=3e-4, n_workers=4, seed=0):
    print(f"\n{'='*64}\nSSL PRETRAIN (steps={steps}, batch={batch})\n{'='*64}")
    ds = SyntheticRoadDataset(n_samples=steps * batch, seed=seed)
    dl = DataLoader(ds, batch_size=batch, num_workers=n_workers,
                    pin_memory=True, drop_last=True, persistent_workers=(n_workers>0))
    opt = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-3)
    warm = 200
    sched = optim.lr_scheduler.LambdaLR(opt, lambda s: min(1.0, (s+1)/warm)
        * max(0.05, 0.5*(1 + math.cos(math.pi * max(0, s-warm)/max(1, steps-warm)))))
    scaler = GradScaler(enabled=(not USE_BF16))
    model = model.to(DEVICE).train()
    it = iter(dl); s = 0; t0 = time.time(); rolling = 0.0
    while s < steps:
        try: x, x_fs, t_rec, t_fs, mask = next(it)
        except StopIteration:
            it = iter(dl); x, x_fs, t_rec, t_fs, mask = next(it)
        x = x.to(DEVICE, non_blocking=True); x_fs = x_fs.to(DEVICE, non_blocking=True)
        t_rec = t_rec.to(DEVICE, non_blocking=True); t_fs = t_fs.to(DEVICE, non_blocking=True)
        mask = mask.to(DEVICE, non_blocking=True)
        opt.zero_grad(set_to_none=True)
        with autocast(dtype=AMP_DTYPE, enabled=torch.cuda.is_available()):
            pr = model(x, mode='recon')                      # (B,L,2)
            pf = model(x_fs, mode='fs')                       # (B,L,2)
            l_rec = ((pr - t_rec).pow(2).mean(-1) * mask).sum() / mask.sum().clamp_min(1.0)
            l_fs  = (pf - t_fs).pow(2).mean()
            loss = l_rec + 0.5 * l_fs
        if USE_BF16:
            loss.backward(); nn.utils.clip_grad_norm_(model.parameters(),1.0); opt.step()
        else:
            scaler.scale(loss).backward(); scaler.unscale_(opt)
            nn.utils.clip_grad_norm_(model.parameters(),1.0)
            scaler.step(opt); scaler.update()
        sched.step()
        rolling = 0.98*rolling + 0.02*loss.item() if s>0 else loss.item()
        s += 1
        if s % 250 == 0 or s == 1:
            print(f"  step {s:5d}/{steps} | loss={rolling:.4f}  ({(time.time()-t0)/60:.1f}m)")
    print(f"  pretrain done in {(time.time()-t0)/60:.1f} min")
    return model

# -------------------- Finetune --------------------
class FocalLoss(nn.Module):
    def __init__(self, gamma=1.5, pos_weight=1.0):
        super().__init__(); self.g=gamma; self.pw=pos_weight
    def forward(self, logits, y):
        bce = F.binary_cross_entropy_with_logits(logits, y, reduction='none')
        w = torch.where(y==1, self.pw, 1.0); bce = bce * w
        pt = torch.where(y==1, torch.sigmoid(logits), 1 - torch.sigmoid(logits))
        return ((1-pt).pow(self.g) * bce).mean()

def finetune(model, X_tr, y_tr, X_va, y_va, *, frac=1.0, epochs=40, batch=384,
             lr=3e-4, freeze_encoder=False, name='SSL-finetune'):
    n = int(len(y_tr) * frac); idx = np.random.RandomState(0).permutation(len(y_tr))[:n]
    X_tr = X_tr[idx]; y_tr = y_tr[idx]
    print(f"\n{'='*64}\n{name} (frac={frac:.2f}, n={n}, freeze_encoder={freeze_encoder})\n{'='*64}")
    model = model.to(DEVICE)            # FIX: from-scratch path created model on CPU
    if freeze_encoder:
        for p in model.enc.parameters(): p.requires_grad = False
    n_pos = y_tr.sum(); pw = (len(y_tr) - n_pos) / max(1, n_pos)
    weights = np.where(y_tr == 1, pw, 1.0)
    sampler = torch.utils.data.WeightedRandomSampler(weights, len(weights), replacement=True)
    Xt = torch.tensor(X_tr, dtype=torch.float32).permute(0, 2, 1)
    yt = torch.tensor(y_tr, dtype=torch.float32)
    dl = DataLoader(TensorDataset(Xt, yt), batch_size=batch, sampler=sampler,
                    num_workers=2, pin_memory=True, drop_last=True)
    Xv = torch.tensor(X_va, dtype=torch.float32).permute(0, 2, 1).to(DEVICE)

    params = [p for p in model.parameters() if p.requires_grad]
    opt = optim.AdamW(params, lr=lr, weight_decay=1e-3)
    warm = 3
    sched = optim.lr_scheduler.LambdaLR(opt, lambda e: (e+1)/warm if e<warm
        else max(0.01, 0.5*(1 + math.cos(math.pi*(e-warm)/max(1, epochs-warm)))))
    crit = FocalLoss(gamma=1.5, pos_weight=pw)
    scaler = GradScaler(enabled=(not USE_BF16))
    best_auc, best_state = 0., None
    for ep in range(epochs):
        model.train(); tot=0; nb=0
        for xb, yb in dl:
            xb=xb.to(DEVICE, non_blocking=True); yb=yb.to(DEVICE, non_blocking=True)
            opt.zero_grad(set_to_none=True)
            with autocast(dtype=AMP_DTYPE, enabled=torch.cuda.is_available()):
                loss = crit(model(xb, mode='cls'), yb)
            if USE_BF16:
                loss.backward(); nn.utils.clip_grad_norm_(params,1.0); opt.step()
            else:
                scaler.scale(loss).backward(); scaler.unscale_(opt)
                nn.utils.clip_grad_norm_(params,1.0)
                scaler.step(opt); scaler.update()
            tot+=loss.item(); nb+=1
        sched.step()
        model.eval()
        with torch.no_grad(), autocast(dtype=AMP_DTYPE, enabled=torch.cuda.is_available()):
            v = torch.sigmoid(model(Xv, mode='cls').float()).cpu().numpy()
        auc = roc_auc_score(y_va, v)
        flag = ' *' if auc > best_auc else ''
        if auc > best_auc:
            best_auc = auc
            best_state = {k: vv.cpu().clone() for k, vv in model.state_dict().items()}
        if (ep+1) % 5 == 0 or flag:
            print(f"  Ep {ep+1:3d} | loss={tot/nb:.4f} | AUC={auc:.4f} | best={best_auc:.4f}{flag}")
    model.load_state_dict(best_state)
    if freeze_encoder:
        for p in model.enc.parameters(): p.requires_grad = True
    return model, best_auc

# -------------------- APFD eval --------------------
def compute_apfd(pids, td):
    n=len(pids)
    fp=[i+1 for i,t in enumerate(pids) if td[t]['meta_data']['test_info']['test_outcome']=='FAIL']
    m=len(fp); return 1 - sum(fp)/(n*m) + 1/(2*n) if n and m else 1.0
def eval_apfd(data, model, means, stds, name=''):
    model.eval().to(DEVICE)
    td={get_id(tc):tc for tc in data}; ids=[get_id(tc) for tc in data]
    feats=[(extract_sequence_10ch(get_pts(tc)) - means)/stds for tc in data]
    X=torch.tensor(np.array(feats), dtype=torch.float32).permute(0,2,1).to(DEVICE)
    with torch.no_grad(), autocast(dtype=AMP_DTYPE, enabled=torch.cuda.is_available()):
        p=torch.sigmoid(model(X, mode='cls').float()).cpu().numpy()
    pids=[t for _,t in sorted(zip(p, ids), key=lambda z:-z[0])]
    a=compute_apfd(pids, td); print(f"  {name:46s} APFD={a:.4f}"); return a
def multi_trial(data, model, means, stds, name='', n_trials=30):
    model.eval().to(DEVICE); apfds=[]
    for t in range(n_trials):
        rng=np.random.RandomState(42+t); idx=rng.permutation(len(data))
        ed=[data[i] for i in idx[334:334+287]]
        td={get_id(tc):tc for tc in ed}; ids=[get_id(tc) for tc in ed]
        feats=[(extract_sequence_10ch(get_pts(tc)) - means)/stds for tc in ed]
        X=torch.tensor(np.array(feats), dtype=torch.float32).permute(0,2,1).to(DEVICE)
        with torch.no_grad(), autocast(dtype=AMP_DTYPE, enabled=torch.cuda.is_available()):
            p=torch.sigmoid(model(X, mode='cls').float()).cpu().numpy()
        pids=[u for _,u in sorted(zip(p, ids), key=lambda z:-z[0])]
        apfds.append(compute_apfd(pids, td))
    print(f"  {name:46s} APFD={np.mean(apfds):.4f}±{np.std(apfds):.4f}")
    return np.mean(apfds)

def prepare_data(data):
    X,y=[],[]
    for i,tc in enumerate(data):
        X.append(extract_sequence_10ch(get_pts(tc))); y.append(1 if is_fail(tc) else 0)
        if (i+1)%5000==0: print(f"    {i+1}/{len(data)}...")
    return np.array(X), np.array(y)

# -------------------- Main --------------------
def main():
    t0=time.time()
    print("\n" + "="*72)
    print("EXP 07 — Geometric Self-Supervised Foundation Model for Roads")
    print("Pretrain: masked-completion + Frenet-Serret on synthetic Bezier roads")
    print("="*72)

    train_data=load_json(TRAIN_PATH); test_data=load_json(TEST_PATH)
    comp_data=load_json(COMP_PATH) if os.path.exists(COMP_PATH) else None

    print("Extracting labelled features...")
    X_tr,y_tr=prepare_data(train_data); X_te,y_te=prepare_data(test_data)
    means=X_tr.mean(axis=(0,1)); stds=X_tr.std(axis=(0,1)); stds[stds<1e-8]=1.0
    X_tr=(X_tr-means)/stds; X_te=(X_te-means)/stds

    # ---- 1) Build foundation, pretrain ----
    fm = FoundationModel(in_channels=10, d_model=256, num_layers=8)
    fm = pretrain(fm, steps=4000, batch=512, lr=3e-4, n_workers=2)
    torch.save({'state': fm.state_dict(),
                'means': means.tolist(), 'stds': stds.tolist()},
               os.path.join(OUTPUT_DIR, 'roadfoundation.pt'))

    # ---- 2) Sample-efficiency curve ----
    print(f"\n{'='*64}\nSAMPLE EFFICIENCY (pretrain vs from-scratch)\n{'='*64}")
    fracs = [0.10, 0.30, 1.00]
    for frac in fracs:
        # 2a) finetune (encoder + heads)
        fm_ft = copy.deepcopy(fm)
        fm_ft, auc = finetune(fm_ft, X_tr, y_tr, X_te, y_te, frac=frac,
                              epochs=40, batch=384, lr=2e-4,
                              freeze_encoder=False, name=f'SSL-finetune {int(frac*100)}%')
        eval_apfd(test_data, fm_ft, means, stds, f'SSL-finetune {int(frac*100)}% SensoDat')
        if comp_data is not None:
            multi_trial(comp_data, fm_ft, means, stds, f'SSL-finetune {int(frac*100)}% multi')

        # 2b) from-scratch baseline (same arch, no pretrain) — control
        fm_scr = FoundationModel(in_channels=10, d_model=256, num_layers=8)
        fm_scr, auc = finetune(fm_scr, X_tr, y_tr, X_te, y_te, frac=frac,
                               epochs=40, batch=384, lr=3e-4,
                               freeze_encoder=False, name=f'from-scratch {int(frac*100)}%')
        eval_apfd(test_data, fm_scr, means, stds, f'scratch {int(frac*100)}% SensoDat')
        if comp_data is not None:
            multi_trial(comp_data, fm_scr, means, stds, f'scratch {int(frac*100)}% multi')

    # ---- 3) Linear probe ----
    print(f"\n{'='*64}\nLINEAR PROBE (encoder frozen)\n{'='*64}")
    fm_lp = copy.deepcopy(fm)
    fm_lp, _ = finetune(fm_lp, X_tr, y_tr, X_te, y_te, frac=1.0,
                        epochs=20, batch=384, lr=5e-4,
                        freeze_encoder=True, name='SSL-linear-probe')
    eval_apfd(test_data, fm_lp, means, stds, 'linear-probe SensoDat')
    if comp_data is not None:
        multi_trial(comp_data, fm_lp, means, stds, 'linear-probe multi')

    print(f"\nTOTAL: {(time.time()-t0)/60:.1f} min")

if __name__ == '__main__':
    main()
